// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_chat from "./routes/api/chat.ts";
import * as $index from "./routes/index.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $Chat from "./islands/Chat.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/chat.ts": $api_chat,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/Chat.tsx": $Chat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
